### ISSUE TITLE
fight scammers in china

### ISSUE THREAD

**Issue by AnIMaPoK** [GDI-foundation/GDI.foundation#13]
Hello, I will explain you the situation, I am a professional poker player, people told me about playing in some Chinese places and I tried, but more than 400,000 rmb have been stolen, after this, I want to fight all this network and that they can not cheat more people

I want to end the system they have, so they can not cheat anyone else, and dirty this mental sport

For example, of the person who cheated me, I have photos to be able to make a facial recognition, but I do not know their personal data because they use the social network wechat with false data.

I would be very grateful if someone helps me with this case, in addition to being cheated out of my own money, they are doing the same with many foreigners for whom online gambling is legal.

greetings and many thanks.

**Comment by cookiemonster** [comment]
Hi @AnIMaPoK
I am not sure how the @GDI-foundation can help you with this as we are a humanitarian non-profit organization. Our mission is to protect the free and open Internet by trying to make it safer and by thus guarding the well-being of humans online, to ensure respect for all human intellectual freedom, and to prevent and mitigate digital abuse. We address security issues with responsible disclosures and assist anywhere in times of need.  Maybe you can ask your government for advice on what is the best course of action?

**Comment by AnIMaPoK** [comment]
Hello! Thanks for answer, I asked and they told me that can't help me, here
the problem, is that we are professional poker players, and a lot of
Chinese people stole us and disappeared, and they are doing this with a lot
of people, they use fake names in WeChat, and is difficult to catch theirs,
but I have one picture, and I can see who is him, only that I haven't got
any real information, if I achieve this, I can do a claim to the Chinese
police because they are fighting this, and we could help Chinese police,
protect professional players, and they stop to stole us, for you have an
idea, I have been stolen by 500.000 RMB. And I would like to fight this
with honour, but I don't have IT knowledge's and fore example, do one
facial recognition from the photo, as I told you, thanks so much ur
response and I wait ur news!
