### ISSUE TITLE
Setup Github nonprofit program

### ISSUE THREAD

**Issue by GDI-foundation** [GDI-foundation/GDI.foundation#19]
---------- Forwarded message ---------
From: GitHub Staff <non-profit@github.com>
Date: Fri, 21 Jun 2019 at 14:58
Subject: Re: Nonprofit account request
To: GDI foundation <@gdi.foundation>

Hello,

Our nonprofit program offers a free [Team Plan](https://github.com/pricing) (unlimited users and unlimited private repositories) to official nonprofit organizations and charities. We just need a little more information from you to get you set up.

You can read more about non-profits on GitHub, including what kinds of information we need, here:

https://github.com/nonprofit

When you're ready to apply, please reply to this email with the following information:

* Your nonprofit’s GitHub organization account name
* Your nonprofit's GitHub organization URL
* Proof of your nonprofit status with your local government (501(c)(3) status in the US)
* The registered name of your nonprofit
* A summary of what your nonprofit organization does
* Confirmation that your organization is nongovernment, nonacademic, noncommercial, nonpolitical and has no religious affiliation

Thank you so much!

**Comment by cookiemonster** [comment]
GitHub organization account name: GDIfoundation
Your nonprofit's GitHub organization URL: https://github.com/GDIfoundation
Proof of your nonprofit status with your local government: https://openkvk.nl/openkvk/rechtspersoon-64762815-stichting-gdifoundation
The registered name of your nonprofit: GDI.foundation
A summary of what your nonprofit organization does:

#### GDI.Foundation is a nonprofit organization. 
Our mission is to defend the free & open Internet by trying to make it safer.
We address security issues with responsible disclosure ([coordinated vulnerability disclosures](https://www.iso.org/standard/45170.html).
 
#### What do we stand for?
We believe that actions must be taken to protect the freedom of communication through the Internet. This is our [mission statement](https://gdi.foundation/mission).

#### What do we do?
We detect & analyze high risk "criminal" opportunities, share the risk & vulnerabilities with everybody, inform the ones who are at risk and give free advice about a solution. Some of our volunteer's work was covered in the [media](https://www.google.nl/search?q=GDI.foundation&num=100&tbs=sbd:1&tbm=nws&tbas=0&source=lnt&sa=X&ved=0ahUKEwi4sMS66qvdAhXGIlAKHdTxC-MQpwUIHw&biw=1440&bih=803&dpr=2).

Confirmation that your organization is nongovernment, nonacademic, noncommercial, nonpolitical and has no religious affiliation: We confirm that we are a nongovernment, nonacademic, noncommercial, nonpolitical and has no religious affiliation as this would conflict with our [mission statement](https://gdi.foundation/mission).

**Comment by GDI-foundation** [comment]
GDI.foundation organization got a Github upgrade. \o/
