### ISSUE TITLE
TheHive docker is not deploying. ElasticSearch will not start on Debian 9

### ISSUE THREAD

**Issue by GDI-foundation** [GDI-foundation/GDI.foundation#4]
Following the instructions for deploying TheHive following these [instructions](https://github.com/TheHive-Project/TheHiveDocs/blob/master/installation/install-guide.md#docker)

Running as root: 
`docker-compose up`
..
cortex_1         | WARNING: An illegal reflective access operation has occurred
cortex_1         | WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/opt/cortex/lib/com.google.inject.guice-4.1.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
cortex_1         | WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
cortex_1         | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
cortex_1         | WARNING: All illegal access operations will be denied in a future release
thehive_1        | Using elasticsearch host: ["172.18.0.3:9300"]
thehive_1        | Add Cortex cortex1: http://172.18.0.2:9001
elasticsearch_1  | [2018-10-01T17:21:23,548][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2018-10-01T17:21:23,948][INFO ][o.e.e.NodeEnvironment    ] [IU8Ervh] using [1] data paths, mounts [[/ (overlay)]], net usable_space [22.3gb], net total_space [29.4gb], spins? [possibly], types [overlay]
elasticsearch_1  | [2018-10-01T17:21:23,948][INFO ][o.e.e.NodeEnvironment    ] [IU8Ervh] heap size [1.9gb], compressed ordinary object pointers [true]
elasticsearch_1  | [2018-10-01T17:21:23,950][INFO ][o.e.n.Node               ] node name [IU8Ervh] derived from node ID [IU8ErvhvQ9mPIDYBCDM9cw]; set [node.name] to override
elasticsearch_1  | [2018-10-01T17:21:23,950][INFO ][o.e.n.Node               ] version[5.6.0], pid[1], build[781a835/2017-09-07T03:09:58.087Z], OS[Linux/4.9.0-8-amd64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_141/25.141-b16]
elasticsearch_1  | [2018-10-01T17:21:23,950][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.cgroups.hierarchy.override=/, -Des.path.home=/usr/share/elasticsearch]
cortex_1         | [info] a.e.s.Slf4jLogger - Slf4jLogger started
cortex_1         | [info] o.e.p.PluginsService - no modules loaded
cortex_1         | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
cortex_1         | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
cortex_1         | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
cortex_1         | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
cortex_1         | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
cortex_1         | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
elasticsearch_1  | [2018-10-01T17:21:27,638][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded module [aggs-matrix-stats]
elasticsearch_1  | [2018-10-01T17:21:27,639][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded module [ingest-common]
elasticsearch_1  | [2018-10-01T17:21:27,639][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded module [lang-expression]
elasticsearch_1  | [2018-10-01T17:21:27,639][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded module [lang-groovy]
elasticsearch_1  | [2018-10-01T17:21:27,639][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded module [lang-mustache]
elasticsearch_1  | [2018-10-01T17:21:27,639][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded module [lang-painless]
elasticsearch_1  | [2018-10-01T17:21:27,639][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded module [parent-join]
elasticsearch_1  | [2018-10-01T17:21:27,639][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded module [percolator]
elasticsearch_1  | [2018-10-01T17:21:27,640][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded module [reindex]
elasticsearch_1  | [2018-10-01T17:21:27,640][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded module [transport-netty3]
elasticsearch_1  | [2018-10-01T17:21:27,640][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded module [transport-netty4]
elasticsearch_1  | [2018-10-01T17:21:27,641][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded plugin [ingest-geoip]
elasticsearch_1  | [2018-10-01T17:21:27,641][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded plugin [ingest-user-agent]
elasticsearch_1  | [2018-10-01T17:21:27,642][INFO ][o.e.p.PluginsService     ] [IU8Ervh] loaded plugin [x-pack]
cortex_1         | [info] i.n.u.i.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
elasticsearch_1  | [2018-10-01T17:21:28,621][WARN ][o.e.d.c.s.Settings       ] [script.inline] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version.
thehive_1        | [info] o.r.Reflections - Reflections took 298 ms to scan 5 urls, producing 121 keys and 1329 values 
...
thehive_1        | [info] a.r.Remoting - Starting remoting
elasticsearch_1  | [2018-10-01T17:21:33,007][INFO ][o.e.x.m.j.p.l.CppLogMessageHandler] [controller/96] [Main.cc@128] controller (64 bit): Version 5.6.0 (Build 93aea61f57f7d8) Copyright (c) 2017 Elasticsearch BV
thehive_1        | [info] a.r.Remoting - Remoting started; listening on addresses :[akka.tcp://application@172.18.0.4:2552]
thehive_1        | [info] a.r.Remoting - Remoting now listens on addresses: [akka.tcp://application@172.18.0.4:2552]
thehive_1        | [info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@172.18.0.4:2552] - Starting up...
elasticsearch_1  | [2018-10-01T17:21:33,097][INFO ][o.e.d.DiscoveryModule    ] [IU8Ervh] using discovery type [zen]
thehive_1        | [info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@172.18.0.4:2552] - Registered cluster JMX MBean [akka:type=Cluster]
thehive_1        | [info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@172.18.0.4:2552] - Started up successfully
thehive_1        | [info] a.c.Cluster(akka://application) - Cluster Node [akka.tcp://application@172.18.0.4:2552] - No seed-nodes configured, manual cluster join required
thehive_1        | [info] o.e.p.PluginsService - no modules loaded
thehive_1        | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
thehive_1        | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
thehive_1        | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
thehive_1        | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
thehive_1        | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty3Plugin]
thehive_1        | [info] o.e.p.PluginsService - loaded plugin [org.elasticsearch.transport.Netty4Plugin]
elasticsearch_1  | [2018-10-01T17:21:35,795][INFO ][o.e.n.Node               ] initialized
elasticsearch_1  | [2018-10-01T17:21:35,795][INFO ][o.e.n.Node               ] [IU8Ervh] starting ...
elasticsearch_1  | [2018-10-01T17:21:36,347][INFO ][o.e.t.TransportService   ] [IU8Ervh] publish_address {172.18.0.3:9300}, bound_addresses {0.0.0.0:9300}
elasticsearch_1  | [2018-10-01T17:21:36,365][INFO ][o.e.b.BootstrapChecks    ] [IU8Ervh] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
elasticsearch_1  | ERROR: [1] bootstrap checks failed
elasticsearch_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch_1  | [2018-10-01T17:21:36,373][INFO ][o.e.n.Node               ] [IU8Ervh] stopping ...
elasticsearch_1  | [2018-10-01T17:21:36,466][INFO ][o.e.n.Node               ] [IU8Ervh] stopped
elasticsearch_1  | [2018-10-01T17:21:36,466][INFO ][o.e.n.Node               ] [IU8Ervh] closing ...
elasticsearch_1  | [2018-10-01T17:21:36,493][INFO ][o.e.n.Node               ] [IU8Ervh] closed
elasticsearch_1  | [2018-10-01T17:21:36,496][INFO ][o.e.x.m.j.p.NativeController] Native controller process has stopped - no new native processes can be started
thehive_1        | [info] i.n.u.i.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
beheerder_elasticsearch_1 exited with code 78
thehive_1        | [info] c.c.s.CortexClient - new Cortex(cortex1, http://172.18.0.2:9001) authentication: no
..
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
cortex_1         | 	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
cortex_1         | 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
cortex_1         | 	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:730)
cortex_1         | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
cortex_1         | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
cortex_1         | 	at com.sksamuel.elastic4s.admin.ClusterExecutables$ClusterStatsExecutable$.apply(ClusterExecutables.scala:38)
cortex_1         | 	at com.sksamuel.elastic4s.admin.ClusterExecutables$ClusterStatsExecutable$.apply(ClusterExecutables.scala:35)
cortex_1         | [info] o.t.c.s.ErrorHandler - GET /api/status returned 500
cortex_1         | org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{KE_1wpYRQyOQf23E3mxiCQ}{172.18.0.3}{172.18.0.3:9300}]
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
cortex_1         | 	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
cortex_1         | 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
cortex_1         | 	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:730)
cortex_1         | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
cortex_1         | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
cortex_1         | 	at com.sksamuel.elastic4s.admin.ClusterExecutables$ClusterStatsExecutable$.apply(ClusterExecutables.scala:38)
cortex_1         | 	at com.sksamuel.elastic4s.admin.ClusterExecutables$ClusterStatsExecutable$.apply(ClusterExecutables.scala:35)
thehive_1        | [info] p.c.s.AkkaHttpServer - Enabling HTTP/2 on Akka HTTP server...
thehive_1        | [info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9000
cortex_1         | [info] o.t.c.s.ErrorHandler - GET /api/user/current returned 500
cortex_1         | org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{KE_1wpYRQyOQf23E3mxiCQ}{172.18.0.3}{172.18.0.3:9300}]
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
cortex_1         | 	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
cortex_1         | 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
cortex_1         | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
cortex_1         | 	at com.sksamuel.elastic4s.search.SearchImplicits$SearchDefinitionExecutable$.$anonfun$apply$1(SearchImplicits.scala:27)
cortex_1         | 	at com.sksamuel.elastic4s.search.SearchImplicits$SearchDefinitionExecutable$.$anonfun$apply$1$adapted(SearchImplicits.scala:27)
cortex_1         | 	at com.sksamuel.elastic4s.Executable.injectFutureAndMap(Executable.scala:21)
cortex_1         | 	at com.sksamuel.elastic4s.Executable.injectFutureAndMap$(Executable.scala:19)
cortex_1         | [info] o.t.c.s.ErrorHandler - GET /api/status returned 500
cortex_1         | org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{KE_1wpYRQyOQf23E3mxiCQ}{172.18.0.3}{172.18.0.3:9300}]
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
cortex_1         | 	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
cortex_1         | 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
cortex_1         | 	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:730)
cortex_1         | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
cortex_1         | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
cortex_1         | 	at com.sksamuel.elastic4s.admin.ClusterExecutables$ClusterStatsExecutable$.apply(ClusterExecutables.scala:38)
cortex_1         | 	at com.sksamuel.elastic4s.admin.ClusterExecutables$ClusterStatsExecutable$.apply(ClusterExecutables.scala:35)
cortex_1         | [info] o.t.c.s.ErrorHandler - GET /api/status returned 500
cortex_1         | org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{KE_1wpYRQyOQf23E3mxiCQ}{172.18.0.3}{172.18.0.3:9300}]
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
cortex_1         | 	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
cortex_1         | 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
cortex_1         | 	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:730)
cortex_1         | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
cortex_1         | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
cortex_1         | 	at com.sksamuel.elastic4s.admin.ClusterExecutables$ClusterStatsExecutable$.apply(ClusterExecutables.scala:38)
cortex_1         | 	at com.sksamuel.elastic4s.admin.ClusterExecutables$ClusterStatsExecutable$.apply(ClusterExecutables.scala:35)
cortex_1         | [info] o.t.c.s.ErrorHandler - GET /api/user/current returned 500
cortex_1         | org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{KE_1wpYRQyOQf23E3mxiCQ}{172.18.0.3}{172.18.0.3:9300}]
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
cortex_1         | 	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
cortex_1         | 	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
cortex_1         | 	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
cortex_1         | 	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
cortex_1         | 	at com.sksamuel.elastic4s.search.SearchImplicits$SearchDefinitionExecutable$.$anonfun$apply$1(SearchImplicits.scala:27)
cortex_1         | 	at com.sksamuel.elastic4s.search.SearchImplicits$SearchDefinitionExecutable$.$anonfun$apply$1$adapted(SearchImplicits.scala:27)
cortex_1         | 	at com.sksamuel.elastic4s.Executable.injectFutureAndMap(Executable.scala:21)
cortex_1         | 	at com.sksamuel.elastic4s.Executable.injectFutureAndMap$(Executable.scala:19)

**Comment by cookiemonster** [comment]
Did you check the rights for the user: elasticsearch?
https://gitter.im/TheHive-Project/TheHive?at=5bae5db656877c463a9b89e4

**Comment by d3adlizard** [comment]
I just bumped the version for elasticsearch to 5.6.12
docker pull docker.elastic.co/elasticsearch/elasticsearch:5.6.12
